name: smart_attend
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies for SmartAttend
  qr_code_scanner: ^1.0.1
  geolocator: ^10.1.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0

  # iOS style icons (optional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
